# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.13.2
_src_path: gh:tsvikas/python-template
format_tool: black
get_package_version_from_vcs: true
github_user: tsvikas
has_cli: true
jupyter_files: forbid
license: MIT
package_description: Sync '.pre-commit-config.yaml' from 'uv.lock'.
package_name: sync_with_uv
project_name: sync-with-uv
python_min: 11
user_email: tsvikas@gmail.com
user_name: Tsvika Shapira
year: 2025
